### ISSUE TITLE
There is no demonstration of datasotre in the project

### ISSUE THREAD

**Issue by BraveMomo** [iamnaran/firefly-compose#2]
There is no datasotre application demonstration in the project, it seems that it is just a dependency, I hope the author can add it, which is very important for many of my newbies, thank youThere is no datasotre application demonstration in the project, it seems that it is just a dependency, I hope the author can add it, which is very important for many of my newbies, thank you!

**Comment by BraveMomo** [comment]
There is also the use of the paging library, there doesn't seem to be a demonstration, only the project dependencies, especially he is used with the room database, I hope you can add to it, this is really important for us newbies, thank you again

**Comment by iamnaran** [comment]
Hi @BraveMomo , thanks for your suggestion! The datastore implementation can be found here -> [Commit](https://github.com/iamnaran/firefly-compose/tree/a206eafd9b62a6796efc91fc7ede20d21087e7ea). I'm currently working on pagination and writing an article about it. 

I haven’t been able to dedicate much time due to other commitments, but I’ll make sure to address the points you mentioned. Thanks again for your feedback!

**Comment by BraveMomo** [comment]
> Hi @BraveMomo , thanks for your suggestion! The datastore implementation can be found here -> [Commit](https://github.com/iamnaran/firefly-compose/tree/a206eafd9b62a6796efc91fc7ede20d21087e7ea). I'm currently working on pagination and writing an article about it.
> 
> I haven’t been able to dedicate much time due to other commitments, but I’ll make sure to address the points you mentioned. Thanks again for your feedback!

Thank you very much,When you implement the pagination function,Can you do it by the way with a page with a horizontal sliding tab implemented by compose,That is, each page is pagination,The top is a dynamic number of tabs,The kind that can slide left and right,In addition, I found a small problem,I added an empty judgment of account password on the basis of your project,It is judged after clicking the login button,But snackbar is only displayed when you click the login button for the first time,Subsequent click on the login button, snackbar's LaunchedEffect is no longer triggered, how can I fix it?

![image](https://github.com/user-attachments/assets/13e251bb-88ad-4547-a3f5-f7cfe02c2a59)
![image](https://github.com/user-attachments/assets/e3a2e368-ad64-45eb-a166-653a383c104c)

**Comment by iamnaran** [comment]
Thank you for your response. I've resolved the snackbar issue and pushed the changes to the main branch.
